FROM ubuntu:latest 
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    rclone \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    g++ \
    curl \
    aria2 \
    sabnzbdplus \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN rclone --version && python --version && g++ --version